version: '2'
services:
  web.root:
    image: nginx:1.13.12
    container_name: web.root
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${HOSTpublic}
      - LETSENCRYPT_HOST=${HOSTpublic}
      - LETSENCRYPT_EMAIL="for notification"
    networks:
      - proxy_nw
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    expose:
      - "80"
networks:
  proxy_nw:
    external: true
